

class SessionControlAPI:
    # contrôle des tâches individuelles
    def pause_task(self, task_id: str) -> None: ...
    def resume_task(self, task_id: str) -> None: ...
    def cancel_task(self, task_id: str) -> None: ...
    def retry_task(self, task_id: str) -> None: ...
    
    # contrôle de la session globale
    def pause_all(self) -> None: ...
    def resume_all(self) -> None: ...
    def set_pool_concurrency(self, pool: str, max_parallel: int) -> None: ...
    
    # introspection
    def snapshot(self) -> SessionSnapshot: ...
    def task_status(self, task_id: str) -> TaskStatus: ...